#ifndef _SYSCALLS_x86_64_H
#define _SYSCALLS_x86_64_H 1
#include "sanitise.h"
#include "syscall.h"
#include "syscalls/syscalls.h"
struct syscalltable syscalls_bsd[] = {
  NULL,
  { .entry = &syscall_exit },
  { .entry = &syscall_fork },
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_close },
  { .entry = &syscall_wait4 },
  NULL,
  { .entry = &syscall_link },
  { .entry = &syscall_unlink },
  NULL,
  { .entry = &syscall_chdir },
  { .entry = &syscall_fchdir },
  { .entry = &syscall_mknod },
  { .entry = &syscall_chmod },
  { .entry = &syscall_chown },
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_getpid },
  NULL,
  NULL,
  { .entry = &syscall_setuid },
  { .entry = &syscall_getuid },
  { .entry = &syscall_geteuid },
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_accept },
  { .entry = &syscall_getpeername },
  { .entry = &syscall_getsockname },
  { .entry = &syscall_access },
  NULL,
  NULL,
  { .entry = &syscall_sync },
  { .entry = &syscall_kill },
  NULL,
  { .entry = &syscall_getppid },
  NULL,
  { .entry = &syscall_dup },
  { .entry = &syscall_pipe },
  { .entry = &syscall_getegid },
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_getgid },
  { .entry = &syscall_sigprocmask },
  NULL,
  NULL,
  { .entry = &syscall_acct },
  { .entry = &syscall_sigpending },
  { .entry = &syscall_sigaltstack },
  NULL,
  { .entry = &syscall_reboot },
  NULL,
  { .entry = &syscall_symlink },
  { .entry = &syscall_readlink },
  { .entry = &syscall_execve },
  { .entry = &syscall_umask },
  { .entry = &syscall_chroot },
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_msync },
  { .entry = &syscall_vfork },
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_munmap },
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_mincore },
  { .entry = &syscall_getgroups },
  { .entry = &syscall_setgroups },
  { .entry = &syscall_getpgrp },
  NULL,
  { .entry = &syscall_setitimer },
  NULL,
  NULL,
  { .entry = &syscall_getitimer },
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_dup2 },
  NULL,
  NULL,
  { .entry = &syscall_select },
  NULL,
  { .entry = &syscall_fsync },
  { .entry = &syscall_setpriority },
  NULL,
  { .entry = &syscall_connect },
  NULL,
  { .entry = &syscall_getpriority },
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_bind },
  NULL,
  { .entry = &syscall_listen },
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_gettimeofday },
  { .entry = &syscall_getrusage },
  { .entry = &syscall_getsockopt },
  NULL,
  { .entry = &syscall_readv },
  { .entry = &syscall_writev },
  { .entry = &syscall_settimeofday },
  { .entry = &syscall_fchown },
  { .entry = &syscall_fchmod },
  NULL,
  { .entry = &syscall_setreuid },
  { .entry = &syscall_setregid },
  { .entry = &syscall_rename },
  NULL,
  NULL,
  { .entry = &syscall_flock },
  NULL,
  NULL,
  { .entry = &syscall_shutdown },
  { .entry = &syscall_socketpair },
  { .entry = &syscall_mkdir },
  { .entry = &syscall_rmdir },
  { .entry = &syscall_utimes },
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_sysctl },
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_setsid },
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_getpgid },
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_statfs },
  { .entry = &syscall_fstatfs },
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_quotactl },
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_waitid },
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_setgid },
  NULL,
  NULL,
  { .entry = &syscall_sigreturn },
  NULL,
  NULL,
  { .entry = &syscall_fdatasync },
  { .entry = &syscall_stat },
  NULL,
  { .entry = &syscall_lstat },
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_setrlimit },
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_lseek },
  { .entry = &syscall_truncate },
  { .entry = &syscall_ftruncate },
  { .entry = &syscall_sysctl },
  { .entry = &syscall_mlock },
  { .entry = &syscall_munlock },
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_poll },
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_getxattr },
  { .entry = &syscall_fgetxattr },
  NULL,
  NULL,
  { .entry = &syscall_removexattr },
  { .entry = &syscall_fremovexattr },
  { .entry = &syscall_listxattr },
  { .entry = &syscall_flistxattr },
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_semctl },
  { .entry = &syscall_semget },
  { .entry = &syscall_semop },
  NULL,
  NULL,
  { .entry = &syscall_msgget },
  NULL,
  NULL,
  { .entry = &syscall_shmat },
  { .entry = &syscall_shmctl },
  { .entry = &syscall_shmdt },
  { .entry = &syscall_shmget },
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_gettid },
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_getsid },
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_mlockall },
  { .entry = &syscall_munlockall },
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_sendfile },
  { .entry = &syscall_stat64 },
  { .entry = &syscall_fstat64 },
  { .entry = &syscall_lstat64 },
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_statfs64 },
  { .entry = &syscall_fstatfs64 },
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_lchown },
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_close },
  { .entry = &syscall_wait4 },
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_accept },
  { .entry = &syscall_msync },
  NULL,
  { .entry = &syscall_select },
  { .entry = &syscall_fsync },
  { .entry = &syscall_connect },
  NULL,
  { .entry = &syscall_readv },
  { .entry = &syscall_writev },
  NULL,
  NULL,
  NULL,
  { .entry = &syscall_waitid },
  { .entry = &syscall_poll },
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
};
#endif
